### ISSUE TITLE
I want to use timetracker REST API inside VSTS extension

### ISSUE THREAD

**Issue by antshc** [7pace/timetracker-rest-api-samplecode#1]
Hi Guys,

I want to use timetracker REST API inside VSTS extension to build charts and reports using Timetracker data.

REST API works very well in Postman and in Sample but when I try to use it inside my custom VSTS extension  and get folowing exception
```
Failed to load https://{mydomain}.timehub.7pace.com/api/rest/workLogs?api-version=3.0-preview&$fromTimestamp=2018-05-01&$count=10: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://{mydomain}.gallerycdn.vsassets.io' is therefore not allowed access.
```

Is it possible to disable Access-Control-Allow-Origin for my domain?

**Comment by kolomik** [comment]
Hello,

Thank you for interest in our REST API. Indeed, we need to disable CORS for everyone =) 
We will inform you when it will be published to our production environment.

**Comment by antshc** [comment]
I have opened tiket (16734) in support@7pace.com,

they started investigate this CORS problem

**Comment by kolomik** [comment]
CORS-fixing update has been deployed

**Comment by antshc** [comment]
Thenk you,

Great work))

**Comment by mlutsan** [comment]
Added worklog from 01.28.2021 15:46 to 01.28.2021 19:46 (4:00)
